[workspace]
members = [
    "src/backend/discord",
    "src/backend/discord_async",
    "src/backend/serial",
    "src/controller",
    "src/config",
]
resolver = "2"

[package]
version = "0.1.0"
edition = "2024"
name = "DS-2000"
build = "build.rs"

[dependencies]
tauri = { version = "2.4", features = [] }
controller = { path = "src/controller" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tauri-plugin-shell = "2.0.0-beta"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
tauri-build = { version = "2.1.0", features = [] }

[workspace.dependencies]
discord = { path = "src/backend/discord" }
discord_async = { path = "src/backend/discord_async" }
serial = { path = "src/backend/serial" }
controller = { path = "src/controller" }
config = { path = "src/config" }

tauri = { version = "2.4", features = [] }
tauri-plugin-shell = "2.0.0-beta"

rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
directories = "6.0"

log = "0.4"
dotenvy = "0.15"
aes-gcm = "0.10"
hex = "0.4"
bytes = { version = "1.6.0" }
tracing = "0.1"

tokio = { version = "1.0", features = ["full"] }
tokio-serial = "5.4"
serial2-tokio = "0.1"
tokio-util = "0.7.15"
futures-util = { version = "0.3", features = ["sink"] }
thiserror = "2.0"
spawned-concurrency = "0.2.2"
spawned-rt = "0.2.2"
