[package]
name = "discord-async"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tokio.workspace = true
serde_json.workspace = true
thiserror.workspace = true
reqwest.workspace = true
rand.workspace = true
spawned-rt.workspace = true
spawned-concurrency.workspace = true

[lib]
path = "./mod.rs"
