[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
common.workspace = true

serde_json.workspace = true
keyring.workspace = true
serde.workspace = true
directories.workspace = true
thiserror.workspace = true
sys-locale.workspace = true
tokio.workspace = true
tracing.workspace = true

[lib]
path = "./mod.rs"
