[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
serial.workspace = true
config.workspace = true
discord.workspace = true
common.workspace = true

tracing.workspace = true
tauri.workspace = true
tauri-plugin-shell.workspace = true
tauri-plugin-autostart.workspace = true
tokio.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[lib]
path = "./mod.rs"
